"""Initial migration

Revision ID: 055e3e64294b
Revises: 
Create Date: 2024-07-03 01:05:18.043553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '055e3e64294b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('request_type', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.drop_index('idx_fk_address_id')
        batch_op.drop_index('idx_fk_store_id')
        batch_op.drop_index('idx_last_name')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('create_date')
        batch_op.drop_column('last_update')
        batch_op.drop_column('store_id')
        batch_op.drop_column('activebool')
        batch_op.drop_column('address_id')
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address_id', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('activebool', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('store_id', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('create_date', sa.DATE(), server_default=sa.text("('now'::text)::date"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_last_name', ['last_name'], unique=False)
        batch_op.create_index('idx_fk_store_id', ['store_id'], unique=False)
        batch_op.create_index('idx_fk_address_id', ['address_id'], unique=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)

    op.drop_table('api_hits')
    # ### end Alembic commands ###
