"""Add status code and response time to APIHit, create APIStats model

Revision ID: 2b2194884368
Revises: 055e3e64294b
Create Date: 2024-07-03 22:46:39.145725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2194884368'
down_revision = '055e3e64294b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('failed_requests', sa.Integer(), nullable=True),
    sa.Column('total_response_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_hits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('response_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_hits', schema=None) as batch_op:
        batch_op.drop_column('response_time')
        batch_op.drop_column('status_code')

    op.drop_table('api_stats')
    # ### end Alembic commands ###
