"""Set default values for APIStats columns

Revision ID: 343d0cfb7b70
Revises: 2b2194884368
Create Date: 2024-07-03 22:53:00.466881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343d0cfb7b70'
down_revision = '2b2194884368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_stats', schema=None) as batch_op:
        batch_op.alter_column('total_requests',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('failed_requests',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_response_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_stats', schema=None) as batch_op:
        batch_op.alter_column('total_response_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('failed_requests',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_requests',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
